Lesson 5 acceptance test
danilpanshin/SOClone pull request #3
Opened 2018-06-17 19:44 UTC by danilpanshin

2018-06-18 08:19 UTC, vkurennov requested changes

2018-06-18 08:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: %i[show]
show, как и new и index для ответа вообще не нужны, потому что все ответы выводятся на странице вопроса и там же должна быть и форма создания нового ответа

2018-06-18 08:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
new и show не нужны

2018-06-18 08:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(id: @question), notice: 'Your answer successfully created.'
Можно проще:  `redirect_to @question, notice: ...`

2018-06-18 08:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +
В начале и конце метода/класса пустые строки не ставятся

2018-06-18 08:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +
Лишняя пустая строка, завершающие end всегда идут подряд, без пустых строк. Как в методах, так и в классах

2018-06-18 08:19 UTC, vkurennov commented on app/controllers/questions_controller.rb
Лишняя пустая строка

2018-06-18 08:19 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def destroy
Убери лишние пустые строки

2018-06-18 08:19 UTC, vkurennov commented on app/models/answer.rb
>    validates :body, presence: true
А вот валидации принято отделять от ассоциаций пустой строкой

2018-06-18 08:19 UTC, vkurennov commented on spec/acceptance/answers/only_author_can_delete_his_answer_spec.rb
> +  scenario 'Some other user tries to delete others answer' do
Похожий сценарий нужен для гостя (незалогиненного юзера)

2018-06-18 08:19 UTC, vkurennov commented on spec/acceptance/answers/write_an_answer_to_the_question_spec.rb
> +
Лишняя пустая строка

2018-06-18 08:19 UTC, vkurennov commented on spec/acceptance/questions/authenticated_user_can_create_spec.rb
> +    fill_in 'Body', with: 'TestQuestionBody'
Это 2 разных сценария - создание вопроса и создание ответа к нему, они относятся к разным фичам, надо их разделить. И при создании вопроса также проверять, что он есть на странице

2018-06-18 08:19 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверить, что вопрос (заголовок и тело) присутсвуют на странице

2018-06-18 08:19 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +
Лишняя пустая строка

2018-06-18 08:19 UTC, vkurennov commented on spec/acceptance/questions/only_author_can_delete_his_question_spec.rb
> +    expect(page).to have_content "The question was deleted."
Нужно проверить, что до удаления заголовок вопроса был на странице, а после - что его больше нет

2018-06-18 08:19 UTC, vkurennov commented on spec/acceptance/questions/only_author_can_delete_his_question_spec.rb
> +
Опять лишние пустые строки

2018-06-18 08:19 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer), question_id: question, user_id: user } }.to change(Answer, :count).by(1)
Почему изменил? Проверка на связь с вопросом должна остаться. А кроме нее, нужно еще добавить тест еще и на связь с юзером

2018-06-18 08:19 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer), question_id: question, user_id: user } }.to change(Answer, :count).by(1)
И  user_id не передается в параметрах, мы получаем его в контроллере через current_user.

2018-06-18 08:19 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { answer: attributes_for(:answer), question_id: question, user_id: user }
user_id не передается в параметрах

2018-06-18 08:19 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
Где тесты на destroy?

2018-06-18 08:19 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +   describe 'DELETE #destroy' do
У тебя в destroy есть условие, это значит, что нужно проверять все варианты - и когда условие выполняется и когда нет. Лучше всего для этого сделать в 2-х контекстах: для автора и для не-автора

2018-06-18 08:19 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
Где тесты на метод `author?`?

2018-06-18 08:19 UTC, vkurennov commented on spec/factories/answers.rb
> +    body "Answer"
Ответы тоже должны быть разными, иначе тест на список ответов будет ложно-положительным

2018-06-18 22:40 UTC, danilpanshin commented on spec/controllers/answers_controller_spec.rb
> +  end
Вот тут тесты красные, весь день не могу понять что не так. Есть подозрения, что это из-за того, что не включен slallow:true

2018-06-18 22:42 UTC, danilpanshin commented on spec/controllers/answers_controller_spec.rb
> +  end
Failure/Error: expect { delete :destroy, params: { id: answer } }.to change(Answer, :count).by(-1)
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"destroy", :controller=>"answers", :id=>#<Answer id: 376, body: "Answer", question_id: 372, created_at: "2018-06-18 22:41:33", updated_at: "2018-06-18 22:41:33", user_id: 632>}

2018-06-18 22:56 UTC, danilpanshin commented on spec/controllers/answers_controller_spec.rb
> +  end
Всё, тесты позеленели, stackoverflow выручил, дело было в 
      delete :destroy, params: { question_id: question, id: answer }

2018-06-19 07:26 UTC, vkurennov requested changes

2018-06-19 07:26 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
У тебя нет вида new и не должно быть, нужно рендерить ту же страницу, с которой была отправлена форма, т.е. старницу вопроса

2018-06-19 07:26 UTC, vkurennov commented on app/models/user.rb
> +
Лишняя пустая строка

2018-06-19 07:26 UTC, vkurennov commented on app/models/question.rb
>    validates :title, :body, presence: true
Не хватает пустой строки перед валидациями

2018-06-19 07:26 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +
Лишняя пустая строка

2018-06-19 07:26 UTC, vkurennov commented on app/views/answers/_form.html.slim
Лишняя пустая строка

2018-06-19 07:26 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +
Лишняя пустая строка

2018-06-19 07:26 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_for @question do |f|
Не хватает вывода ошибок валидации

2018-06-19 07:26 UTC, vkurennov commented on app/views/answers/_form.html.slim
>    p
Не хватает вывода ошибок валидации

2018-06-19 07:26 UTC, vkurennov commented on spec/acceptance/answers/write_an_answer_to_the_question_spec.rb
> +    expect(page).to have_content question.title
Не нужно проверять наличие вопроса на странице, это ты делаешь в другом тесте. Здесь только сценарий на создание ответа

2018-06-19 07:26 UTC, vkurennov commented on spec/acceptance/answers/write_an_answer_to_the_question_spec.rb
> +feature 'Write an answer', %q{
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю

2018-06-19 07:26 UTC, vkurennov commented on spec/acceptance/questions/authenticated_user_can_create_question_spec.rb
> +feature 'Authenticated user can create questions', %q{
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю

2018-06-19 07:26 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +require 'rails_helper'
Чем эта фича отличается от той, что описывается в `authenticated_user_can_create_question_spec.rb`? И зачем дважды тестировать одно и то же?

2018-06-19 07:26 UTC, vkurennov commented on spec/acceptance/questions/only_author_can_delete_his_question_spec.rb
> +  scenario 'User tries to delete question of another user' do
Похожий сценарий нужен для гостя

2018-06-19 07:26 UTC, vkurennov commented on spec/acceptance/questions/only_author_can_delete_his_question_spec.rb
> +
Лишние пустые строки

2018-06-19 07:26 UTC, vkurennov commented on spec/acceptance/questions/watch_questions_list_spec.rb
> +
Лишняя пустая строка

2018-06-19 07:26 UTC, vkurennov commented on spec/factories/answers.rb
> +    body "Answer"
Ответ по-прежнему имеет только тодно значение поля body - "Answer", т.е. оно жестко задано, что делает тесты на просмотр списка ответов ложно-положительными. У тебя же даже sequence есть для body, нужно здесь просто убрать фиксированное значение атрибута

2018-06-19 07:26 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.id).to eq question.user_id
Ты проверяешь здесь не работу метода `author?`, а работу ассоциаций (т.е. не свой код, а код ActiveRecord). Нельзя написать тесты на метод, не вызывая этого метода. Тебе нужно проверить, что возвращает метод в том или ином случае.

2018-06-19 22:03 UTC, danilpanshin commented on spec/models/user_spec.rb
> +
По идее же должно работать так? Но не работает. Ответ так и не нашел, реализовал чуть проще

2018-06-20 08:32 UTC, vkurennov approved these changes

2018-06-20 08:32 UTC, vkurennov commented on app/views/questions/new.html.slim
> +  p= f.label :title
А зачем тогда у тебя паршл `questions/_form`?

2018-06-20 08:32 UTC, vkurennov commented on spec/models/user_spec.rb
> +
Да, только знак вопроса нужно убрать, должно быть:

`expect(user).to be_author(question)`

rspec динамически определяет по такой конструкции какой метод вызвать. Из матчера `be_author` удаляется `be_` и добавляется знак вопроса. Т.к. ты уже включил знак вопроса, то rspec пытается вызват метод `author??` и не находит его. Думаю, что об этом он пишет в логе и если вниамтельно его посмотреть, то можно увидеть двойной знак вопроса.

2018-06-20 18:24 UTC, merged